/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Controller;

import java.awt.Color;

/**
 *
 * @author trieu
 */
public class ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form ThongKe
     */
    public ThongKe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTKPN = new javax.swing.JButton();
        btnDSPN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnTKPX = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnDSPX = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(java.awt.Color.darkGray);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_resources/THONG KE PN.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTKPN.setText("Thống Kê Phiếu nhập");
        btnTKPN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTKPNMouseMoved(evt);
            }
        });
        btnTKPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKPNMouseExited(evt);
            }
        });
        btnTKPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPNActionPerformed(evt);
            }
        });

        btnDSPN.setText("Danh sách phiếu nhập");
        btnDSPN.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDSPNMouseMoved(evt);
            }
        });
        btnDSPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDSPNMouseExited(evt);
            }
        });
        btnDSPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSPNActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_resources/THONG KE PX.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnTKPX.setText("Thống Kê Phiếu Xuất");
        btnTKPX.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnTKPXMouseMoved(evt);
            }
        });
        btnTKPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTKPXMouseExited(evt);
            }
        });
        btnTKPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPXActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_resources/XEM DS PN.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnDSPX.setText("Danh sách phiếu xuất");
        btnDSPX.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDSPXMouseMoved(evt);
            }
        });
        btnDSPX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDSPXMouseExited(evt);
            }
        });
        btnDSPX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSPXActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image_resources/XEM DS PX.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(btnTKPN, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTKPX, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnDSPN, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDSPX, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(189, 189, 189)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTKPN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTKPX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDSPN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDSPX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDSPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSPNActionPerformed
        ThongKe_DSPN_Dialog thongKe_DSPN_Dialog = new ThongKe_DSPN_Dialog(null, true);
        thongKe_DSPN_Dialog.setVisible(true);
    }//GEN-LAST:event_btnDSPNActionPerformed

    private void btnDSPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDSPXActionPerformed
        ThongKe_DSPX_Dialog thongKe_DSPX_Dialog = new ThongKe_DSPX_Dialog(null, true);
        thongKe_DSPX_Dialog.setVisible(true);
    }//GEN-LAST:event_btnDSPXActionPerformed

    private void btnTKPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPNActionPerformed
        ThongKe_SLPN thongKe_SLPN = new ThongKe_SLPN();

    }//GEN-LAST:event_btnTKPNActionPerformed

    private void btnTKPXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPXActionPerformed
        
        ThongKe_SLPX thongKe_SLPX = new ThongKe_SLPX();
    }//GEN-LAST:event_btnTKPXActionPerformed

    private void btnTKPNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPNMouseMoved
        btnTKPN.setToolTipText("Click vào để xem thống kê những phiếu Nhập đã nhập trong 1 năm!");
        btnTKPN.setBackground(Color.blue);
        btnTKPN.setForeground(Color.white);
    }//GEN-LAST:event_btnTKPNMouseMoved

    private void btnTKPXMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPXMouseMoved
        btnTKPX.setToolTipText("Click vào để xem thống kê những phiếu Xuất đã xuất trong 1 năm!");
        btnTKPX.setBackground(Color.blue);
        btnTKPX.setForeground(Color.white);
    }//GEN-LAST:event_btnTKPXMouseMoved

    private void btnDSPNMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSPNMouseMoved
        btnDSPN.setToolTipText("Click vào để xem thống kê danh sách phiếu nhập từ trước đến nay!");
        btnDSPN.setBackground(Color.blue);
        btnDSPN.setForeground(Color.white);
    }//GEN-LAST:event_btnDSPNMouseMoved

    private void btnDSPXMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSPXMouseMoved
        btnDSPX.setToolTipText("Click vào để xem thống kê danh sách phiếu xuất từ trước đến nay!");
        btnDSPX.setBackground(Color.blue);
        btnDSPX.setForeground(Color.white);

    }//GEN-LAST:event_btnDSPXMouseMoved

    private void btnTKPNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPNMouseExited
        btnTKPN.setBackground(Color.white);
        btnTKPN.setForeground(Color.black);
    }//GEN-LAST:event_btnTKPNMouseExited

    private void btnDSPNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSPNMouseExited
        btnDSPN.setBackground(Color.white);
        btnDSPN.setForeground(Color.black);
    }//GEN-LAST:event_btnDSPNMouseExited

    private void btnTKPXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTKPXMouseExited
        btnTKPX.setBackground(Color.white);
        btnTKPX.setForeground(Color.black);
    }//GEN-LAST:event_btnTKPXMouseExited

    private void btnDSPXMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDSPXMouseExited
        btnDSPX.setBackground(Color.white);
        btnDSPX.setForeground(Color.black);
    }//GEN-LAST:event_btnDSPXMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSPN;
    private javax.swing.JButton btnDSPX;
    private javax.swing.JButton btnTKPN;
    private javax.swing.JButton btnTKPX;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
